advanced:
  max_retries: 3
  reddit_rate_limit_delay: 1
  retry_delay: 5
  user_agent: FragDropDetector/1.0 (by u/cc_apt107)
database:
  path: data/fragdrop.db
  retention_days: 30
detection:
  confidence_threshold: 0.8
  exclusion_keywords:
  - looking for
  - where to buy
  - wtb
  - wts
  - iso
  - recommendation
  - review
  known_vendors:
  - montagneparfums
  - montagne_parfums
  primary_keywords:
  - drop
  - restock
  secondary_keywords:
  - limited
  trusted_authors:
  - ayybrahamlmaocoln
  - wide_parsley1799
  - montagneparfums
  - mpofficial
drop_window:
  days_of_week:
  - 4
  enabled: true
  end_hour: 18
  end_minute: 0
  start_hour: 12
  start_minute: 0
  timezone: America/New_York
logging:
  auto_cleanup:
    cache_max_age_days: 7
    clean_cache: true
    cleanup_interval_hours: 24
    compress_old_logs: true
    enabled: true
    max_age_days: 30
    max_total_size_mb: 100
  backup_count: 5
  file_enabled: true
  file_path: logs/fragdrop.log
  level: INFO
  max_file_size: 10
monitoring:
  health_check_enabled: false
  health_check_port: 8080
notifications:
  discord:
    enabled: true
  email:
    enabled: false
  pushover:
    enabled: true
  send_test_on_start: false
parfumo:
  auto_scrape_new: true
  enabled: true
  last_update: null
  update_time: '02:00'
reddit:
  check_interval: 300
  post_limit: 50
  subreddit: MontagneParfums
stock_monitoring:
  enabled: true
  notifications:
    new_products: true
    out_of_stock: false
    price_changes: false
    restocked_products: true
  watchlist: []
stock_schedule:
  check_interval: 900
  days_of_week: []
  enabled: true
  end_hour: 18
  end_minute: 0
  start_hour: 9
  start_minute: 0
  timezone: America/New_York
  window_enabled: false
