advanced:
  max_retries: 3
  reddit_rate_limit_delay: 1
  retry_delay: 5
  user_agent: FragDropDetector/1.0 (by /u/YourRedditUsername)
database:
  path: data/fragdrop.db
  retention_days: 30
detection:
  confidence_threshold: 0.4
  known_vendors:
  - montagneparfums
  - montagne_parfums
  primary_keywords:
  - drop
  - dropped
  - dropping
  - release
  - released
  - available
  - launch
  - restock
  - in stock
  - now live
  - new fragrance
  - new perfume
  secondary_keywords:
  - limited
  - exclusive
  - special
  - pre-order
  - sale
  - discount
  - batch
  - decant
  - split
  - bottle
  - price
  - order
  - link
drop_window:
  days_of_week:
  - 4
  enabled: true
  end_hour: 18
  end_minute: 0
  start_hour: 12
  start_minute: 0
  timezone: America/New_York
logging:
  backup_count: 5
  file_enabled: true
  file_path: logs/fragdrop.log
  level: INFO
  max_file_size: 10
monitoring:
  health_check_enabled: false
  health_check_port: 8080
notifications:
  discord:
    enabled: true
  email:
    enabled: false
  pushover:
    enabled: true
  send_test_on_start: false
reddit:
  check_interval: 300
  post_limit: 50
  subreddit: MontagneParfums
stock_monitoring:
  enabled: true
  notifications:
    new_products: true
    out_of_stock: false
    price_changes: false
    restocked_products: true
  watchlist:
  - pineappleroyale
